server:
  port: 8002

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:7002/loyalty-program-customers-service?currentSchema=public
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:7002/loyalty-program-customers-service?currentSchema=public
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
